#!/usr/bin/env bash
# duplicate web-01 to web-02
# these scripts are an upgrade from the web-server scripts...

# uncomment to see the script run in action
#set -x

#updating packages
sudo apt-get update
sudo apt-get install -y nginx

#creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

#perform a rediraction
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/reign001 permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites_enabled/default

# creating a custom error page
echo "ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom HTTP response header

sudo sed -i "server_name _;/a add_header X-Served-by $HOSTNAME;" /etc/nginx/site_enabled/default

#Test for syntax errors
sudo nginx -t

#restart nginx
udo service nginx restart
