#!/usr/bin/env bash
# A script that uses ssh to connect to server
server_ip="your_server_ip"
user="ubuntu"
private_key="~/.ssh/school"

# SSH connection using single-character flags
ssh -i "$private_key" "$user"@"$server_ip"

