#!/usr/bin/env bash
# a script for SSH client configuration
Host *
   PasswordAuthentication no
   IdentityFile ~/.ssh/school
   SendEnv LANG LC_*
   ChallengeResponseAuthentication no
   HashKnownHost yes
   GSSAPIAuthentication yes
   GSSAPIDelegateCredentials no
